language: minimal
addons:
  apt:
    update: true
    packages:
    - texlive-full
  homebrew:
    update: true
    casks:
    - mactex
jobs:
  include:
  - name: "ubuntu 16.04 - texlive 2015"
    os: linux
    dist: xenial
  - name: "ubuntu 18.04 - texlive 2017"
    os: linux
    dist: bionic
  - name: "osx - mactex from homebrew - texlive 2019"
    os: osx
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then tlmgr path add; fi
script:
  - latexmk -pdf -interaction=nonstopmode -halt-on-error *.tex