language: minimal
addons:
  apt:
    #update: true
    packages:
    - texlive-full
  homebrew:
    update: true
    casks:
    - mactex
jobs:
  include:
  - name: "ubuntu 16.04 - texlive 2015"
    os: linux
    dist: xenial
  - name: "ubuntu 18.04 - texlive 2017"
    os: linux
    dist: bionic
  - name: "osx - mactex from homebrew - texlive 2019"
    os: osx
script:
  - pdflatex -interaction=nonstopmode -halt-on-error midl-sampleabstract
  - bibtex midl-sampleabstract
  - pdflatex -interaction=nonstopmode -halt-on-error midl-sampleabstract
  - pdflatex -interaction=nonstopmode -halt-on-error midl-sampleabstract